name: "build-latest"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "master"
    paths:
      - "Dockerfile*"
  pull_request:
    branches:
      - "main"
      - "master"
    paths:
      - "Dockerfile*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  docker_buildx_alpine:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract the Nginx version numbers from the Dockerfile
        id: tagger
        run: bash .github/version_extractor.sh ./Dockerfile >> $GITHUB_ENV

      - name: Build and push latest Alpine image with all tags
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:alpine
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:mainline-alpine
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.NGINX_MAJOR }}-alpine
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.NGINX_MAJOR }}.${{ env.NGINX_MINOR }}-alpine
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.NGINX_MAJOR }}.${{ env.NGINX_MINOR }}.${{ env.NGINX_PATCH }}-alpine
